import json
import logging
from typing import List, Dict, Any
import httpx
from app.config import settings

# Setup logger
logger = logging.getLogger("app.ai_service")
logging.basicConfig(level=logging.INFO)

def generate_ai_response(prompt: str, json_format: bool = False) -> str:
    """
    Directly communicates with the local Ollama instance using HTTP requests.
    
    Args:
        prompt: The complete formatted prompt text.
        json_format: If True, instructs Ollama to return the output in structured JSON.
        
    Returns:
        The text response generated by the local Ollama model.
    """
    base_url = settings.OLLAMA_BASE_URL
    model_name = settings.OLLAMA_MODEL
    url = f"{base_url.rstrip('/')}/api/generate"
    
    payload = {
        "model": model_name,
        "prompt": prompt,
        "stream": False,
        "options": {
            "temperature": 0.3
        }
    }
    
    if json_format:
        payload["format"] = "json"

    try:
        # Set a generous timeout since local generation on CPUs can take time
        with httpx.Client(timeout=90.0) as client:
            response = client.post(url, json=payload)
            
            # Handle specific Ollama API errors
            if response.status_code == 404:
                raise ValueError(
                    f"Ollama returned 404. Either the API path is incorrect or the model '{model_name}' "
                    f"is not downloaded. Please run 'ollama pull {model_name}' in your terminal."
                )
            elif response.status_code != 200:
                raise RuntimeError(
                    f"Ollama returned HTTP status {response.status_code}: {response.text}"
                )
                
            res_data = response.json()
            res_content = res_data.get("response", "").strip()
            
            if not res_content:
                raise ValueError("Received empty response text from local Ollama model.")
                
            return res_content
            
    except httpx.ConnectError as ce:
        logger.error(f"Failed to connect to local Ollama service: {str(ce)}")
        raise ConnectionError(
            f"Could not connect to Ollama at '{base_url}'. Please ensure that Ollama is "
            f"installed and the service is actively running on your machine."
        )
    except Exception as e:
        logger.error(f"Error calling local Ollama service: {str(e)}")
        # Propagate custom value or connection errors as is, otherwise wrap
        if isinstance(e, (ValueError, ConnectionError)):
            raise e
        raise RuntimeError(f"Ollama integration error: {str(e)}")

def generate_answer(query: str, context_chunks: List[str]) -> str:
    """
    Generates a contextual response to a user's query based on retrieved PDF text segments.
    
    Args:
        query: The user's question.
        context_chunks: Top semantic matches from the vector database.
        
    Returns:
        An elegant, markdown-friendly text answer.
    """
    if not context_chunks:
        return "I couldn't find any relevant information in the uploaded document to answer that question. Could you please ask something else or try another section?"
        
    context = "\n---\n".join(context_chunks)
    
    prompt = f"""You are a brilliant AI Document Assistant.
Use the following extracted context segments from a PDF document to answer the User Question accurately, clearly, and elegantly.

If the answer cannot be directly derived from the document context, formulate your best logical answer using general knowledge but explicitly prepend your response with a brief note stating: "[Note: This answer is supplemented with general knowledge as it is not explicitly detailed in the document.]"

Format your answer with neat bullet points, bold headers, or code blocks where appropriate for high readability.

Document Context:
---
{context}
---

User Question: {query}

Assistant Response:"""
    
    return generate_ai_response(prompt)

def are_questions_similar(q1: str, q2: str, threshold: float = 0.7) -> bool:
    """
    Checks if two questions are lexically similar to prevent duplicates.
    """
    words1 = set(q1.lower().replace("?", "").replace(".", "").replace(",", "").split())
    words2 = set(q2.lower().replace("?", "").replace(".", "").replace(",", "").split())
    if not words1 or not words2:
        return False
    intersection = words1.intersection(words2)
    overlap = len(intersection) / min(len(words1), len(words2))
    return overlap >= threshold

def get_diverse_sample_text(document_text: str, max_chars: int = 6000) -> str:
    """
    Extracts distributed segments from across the entire document text to ensure variety.
    """
    document_text = document_text.strip()
    if len(document_text) <= max_chars:
        return document_text
        
    num_segments = 5
    segment_size = len(document_text) // num_segments
    extracted_parts = []
    chars_per_segment = max_chars // num_segments
    
    for i in range(num_segments):
        start_idx = i * segment_size
        chunk = document_text[start_idx : start_idx + chars_per_segment]
        extracted_parts.append(f"[Section {i+1}]\n{chunk.strip()}")
        
    return "\n\n...\n\n".join(extracted_parts)

def generate_quiz(document_text: str, num_questions: int = 5) -> List[Dict[str, Any]]:
    """
    Analyzes the raw text contents of the PDF and generates a structured multiple-choice quiz.
    Uses segment-based context sampling, multi-attempt validation, and semantic overlap checks.
    
    Args:
        document_text: The source text parsed from the PDF.
        num_questions: Number of questions to generate.
        
    Returns:
        A list of dictionary objects representing quiz questions.
    """
    if not document_text.strip():
        raise ValueError("The uploaded document has no readable text to generate a quiz from.")
        
    sample_text = get_diverse_sample_text(document_text)
    
    valid_questions = []
    seen_question_texts = []
    
    # Run up to 3 generation attempts to fill the quiz requirement
    for attempt in range(3):
        needed = num_questions - len(valid_questions)
        if needed <= 0:
            break
            
        logger.info(f"Quiz Generation Attempt {attempt + 1}: Generating {needed} questions (Target total: {num_questions})")
        
        exclude_instruction = ""
        if seen_question_texts:
            exclude_list = "\n".join([f"- {q}" for q in seen_question_texts])
            exclude_instruction = f"""
DO NOT generate questions that are identical or semantically similar to these existing questions:
{exclude_list}
"""

        prompt = f"""You are an educational tutor. Your task is to generate a comprehensive multiple-choice quiz based on the document text provided.
Generate exactly {needed} high-quality, unique and relevant questions.

{exclude_instruction}

You MUST reply ONLY with a valid, raw JSON object containing a "quiz" key whose value is a list of question objects. Do not wrap the JSON output in markdown formatting like ```json ... ```, and do not add any surrounding explanatory or greeting text.

The JSON response MUST follow this structure:
{{
  "quiz": [
    {{
      "id": 1,
      "question": "Question text?",
      "options": ["Option A", "Option B", "Option C", "Option D"],
      "correct_answer": "Option A"
    }}
  ]
}}

Requirements for each question:
- Every question MUST have exactly 4 unique options in the "options" list.
- The "correct_answer" MUST be exactly identical to one of the values inside the "options" list.
- Focus on different parts of the document context to ensure variety.

Document Text:
---
{sample_text}
---

JSON Output:"""

        try:
            raw_response = generate_ai_response(prompt, json_format=True).strip()
            
            clean_response = raw_response
            if clean_response.startswith("```"):
                # Remove starting/ending code blocks
                lines = clean_response.splitlines()
                if lines[0].startswith("```"):
                    lines = lines[1:]
                if lines and lines[-1].startswith("```"):
                    lines = lines[:-1]
                clean_response = "\n".join(lines).strip()
                
            quiz_data = json.loads(clean_response)
            
            # Robust dictionary-to-list extraction
            if isinstance(quiz_data, dict):
                for key in ["quiz", "questions", "items", "results"]:
                    if key in quiz_data and isinstance(quiz_data[key], list):
                        quiz_data = quiz_data[key]
                        break
                else:
                    quiz_data = [quiz_data]
                    
            if not isinstance(quiz_data, list):
                logger.warning(f"Parsed data from attempt {attempt + 1} was not a list, retrying...")
                continue
                
            for item in quiz_data:
                # Validation checks
                if "question" not in item or "options" not in item or "correct_answer" not in item:
                    logger.warning(f"Skipping quiz item: missing required keys. Item keys: {list(item.keys()) if hasattr(item, 'keys') else type(item)}")
                    continue
                    
                q_text = item["question"].strip()
                options = item["options"]
                correct = item["correct_answer"].strip()
                
                # Check 1: Semantic duplication check
                is_duplicate = False
                for seen in seen_question_texts:
                    if are_questions_similar(q_text, seen):
                        is_duplicate = True
                        break
                if is_duplicate:
                    logger.warning(f"Skipping quiz item: semantically similar to an existing question: '{q_text}'")
                    continue
                    
                # Check 2: Option count check (Exactly 4)
                if not isinstance(options, list) or len(options) != 4:
                    logger.warning(f"Skipping quiz item: options count is {len(options) if isinstance(options, list) else 'not a list'} instead of 4.")
                    continue
                    
                # Clean options
                options = [str(opt).strip() for opt in options]
                
                # Check 3: Option uniqueness check
                if len(set(options)) != 4:
                    logger.warning(f"Skipping quiz item: options are not unique: {options}")
                    continue
                    
                # Check 4: Correct answer presence check
                if correct not in options:
                    logger.warning(f"Skipping quiz item: correct answer '{correct}' is not found in options: {options}")
                    continue
                    
                # Passed all checks!
                valid_questions.append({
                    "id": len(valid_questions) + 1,
                    "question": q_text,
                    "options": options,
                    "correct_answer": correct
                })
                seen_question_texts.append(q_text)
                
                if len(valid_questions) >= num_questions:
                    break
                    
        except Exception as e:
            logger.error(f"Error parsing quiz JSON in attempt {attempt + 1}: {str(e)}")
            
    # Fallback to default questions only if no valid questions could be generated
    if not valid_questions:
        logger.warning("Failed to generate any valid quiz questions from document context. Returning fallback troubleshooting quiz.")
        return [
            {
                "id": 1,
                "question": "We couldn't generate a custom quiz for this document because of an offline AI formatting issue. Make sure Ollama is fully running with llama3.2:3b and try again.",
                "options": [
                    "Yes, try regenerating now",
                    "No, I will review the Ollama service status first",
                    "Verify model 'llama3.2:3b' is pulled",
                    "Check server logs for error trace"
                ],
                "correct_answer": "Yes, try regenerating now"
            },
            {
                "id": 2,
                "question": "What is the recommended command to verify that Ollama is working and the model is downloaded?",
                "options": [
                    "ollama run llama3.2:3b",
                    "ollama list",
                    "Both of the above",
                    "None of the above"
                ],
                "correct_answer": "Both of the above"
            }
        ]
        
    return valid_questions

