import json
import logging
from typing import List, Dict, Any
from app.config import settings

# Setup logger
logger = logging.getLogger("app.ai_service")
logging.basicConfig(level=logging.INFO)

def generate_ai_response(prompt: str) -> str:
    """
    Directly communicates with the chosen LLM provider (Gemini or Groq) using a system prompt.
    
    Args:
        prompt: The complete formatted prompt text.
        
    Returns:
        The text response generated by the AI model.
    """
    provider = settings.API_PROVIDER
    api_key = settings.api_key
    
    # Validate API Key presence and structure
    if not api_key or "your_" in api_key or api_key.strip() == "":
        raise ValueError(
            f"API key for '{provider.upper()}' is missing or is set to a placeholder in the .env file. "
            f"Please create/update your .env file with a valid API key."
        )

    try:
        if provider == "gemini":
            import google.generativeai as genai
            genai.configure(api_key=api_key)
            # Using stable and free-tier friendly gemini-2.5-flash
            model = genai.GenerativeModel(
                model_name="gemini-2.5-flash",
                generation_config={"temperature": 0.3}
            )
            response = model.generate_content(prompt)
            if not response.text:
                raise ValueError("Received empty response text from Gemini API.")
            return response.text
            
        elif provider == "groq":
            from groq import Groq
            client = Groq(api_key=api_key)
            # Using fast and stable Llama-3-8b-8192
            completion = client.chat.completions.create(
                model="llama3-8b-8192",
                messages=[{"role": "user", "content": prompt}],
                temperature=0.3
            )
            res_content = completion.choices[0].message.content
            if not res_content:
                raise ValueError("Received empty content from Groq API.")
            return res_content
            
        else:
            raise ValueError(f"Unsupported API provider configuration: '{provider}'")
            
    except Exception as e:
        logger.error(f"Error calling {provider.upper()} API: {str(e)}")
        raise RuntimeError(f"AI API request failed: {str(e)}")

def generate_answer(query: str, context_chunks: List[str]) -> str:
    """
    Generates a contextual response to a user's query based on retrieved PDF text segments.
    
    Args:
        query: The user's question.
        context_chunks: Top semantic matches from the vector database.
        
    Returns:
        An elegant, markdown-friendly text answer.
    """
    if not context_chunks:
        return "I couldn't find any relevant information in the uploaded document to answer that question. Could you please ask something else or try another section?"
        
    context = "\n---\n".join(context_chunks)
    
    prompt = f"""You are a brilliant AI Document Assistant.
Use the following extracted context segments from a PDF document to answer the User Question accurately, clearly, and elegantly.

If the answer cannot be directly derived from the document context, formulate your best logical answer using general knowledge but explicitly prepend your response with a brief note stating: "[Note: This answer is supplemented with general knowledge as it is not explicitly detailed in the document.]"

Format your answer with neat bullet points, bold headers, or code blocks where appropriate for high readability.

Document Context:
---
{context}
---

User Question: {query}

Assistant Response:"""
    
    return generate_ai_response(prompt)

def generate_quiz(document_text: str, num_questions: int = 5) -> List[Dict[str, Any]]:
    """
    Analyzes the raw text contents of the PDF and generates a structured multiple-choice quiz.
    
    Args:
        document_text: The source text parsed from the PDF.
        num_questions: Number of questions to generate.
        
    Returns:
        A list of dictionary objects representing quiz questions.
    """
    # Sample the text to prevent token length issues
    sample_text = document_text[:5000].strip()
    if not sample_text:
        raise ValueError("The uploaded document has no readable text to generate a quiz from.")

    prompt = f"""You are an educational tutor. Your task is to generate a comprehensive multiple-choice quiz based on the document text provided.
Generate exactly {num_questions} high-quality, relevant questions.

You MUST reply ONLY with a valid, raw JSON array of objects. Do not wrap the JSON output in markdown formatting like ```json ... ```, and do not add any surrounding explanatory or greeting text.

Each object in the JSON array must follow this exact schema:
{{
  "id": 1,
  "question": "The text of the question?",
  "options": ["Option A text", "Option B text", "Option C text", "Option D text"],
  "correct_answer": "Option A text"
}}

Ensure the 'correct_answer' exactly matches one of the values inside the 'options' list.

Document Text:
---
{sample_text}
---

JSON Output:"""

    raw_response = generate_ai_response(prompt).strip()
    
    # Robust clean-up if the LLM outputted markdown wraps despite the instruction
    clean_response = raw_response
    if clean_response.startswith("```"):
        # Remove starting code block line
        lines = clean_response.splitlines()
        if lines[0].startswith("```"):
            lines = lines[1:]
        if lines and lines[-1].startswith("```"):
            lines = lines[:-1]
        clean_response = "\n".join(lines).strip()
        
    try:
        quiz_data = json.loads(clean_response)
        if not isinstance(quiz_data, list):
            raise ValueError("Parsed data is not a JSON list array.")
        
        # Verify schema integrity for each item
        for i, item in enumerate(quiz_data):
            item["id"] = i + 1
            if "question" not in item or "options" not in item or "correct_answer" not in item:
                raise KeyError("Missing required keys in quiz item.")
            if not isinstance(item["options"], list) or len(item["options"]) < 2:
                raise ValueError("Options must be a list containing at least 2 choices.")
            if item["correct_answer"] not in item["options"]:
                # Gracefully fix if it doesn't match exactly by selecting the first option as fallback
                item["options"].append(item["correct_answer"])
                
        return quiz_data
        
    except Exception as e:
        logger.error(f"Error parsing quiz JSON from response. Raw response was:\n{raw_response}\nError details: {str(e)}")
        # Provide an interactive, descriptive fallback quiz explaining that parsing failed
        return [
            {
                "id": 1,
                "question": "We couldn't generate a custom quiz for this document because of an AI JSON formatting issue. Would you like to try again?",
                "options": [
                    "Yes, try regenerating now",
                    "No, I will review the API configurations first",
                    "Try uploading a smaller document",
                    "API key setup is incomplete"
                ],
                "correct_answer": "Yes, try regenerating now"
            },
            {
                "id": 2,
                "question": "What is the recommended next step when you receive this fallback message?",
                "options": [
                    "Check the server logs to see the raw API output",
                    "Re-upload the PDF to trigger a fresh parsing session",
                    "Ensure your GEMINI_API_KEY or GROQ_API_KEY is correct in .env",
                    "All of the above"
                ],
                "correct_answer": "All of the above"
            }
        ]
